apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: nodejsapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejsapp 
    spec:
      containers:
        - name: nodejsapp 
          image: nodejsappregistry.azurecr.io/nodejsapp
          ports:
          - containerPort: 3000